run_name: regression_micro_${net.arch}
experiment: RegressionExperiment

target_indices: [0,1,2,3,4,5]
loss: l2

data:
  dir: /scratch/ore/data/x5
  file_by_file: False
  
net:
  use_head: True
  out_channels: 6 # length of target_indices

training:
  lr: 1.e-4

defaults:
  - default
  - preprocessing: xandy
  - net: vit_micro
  - _self_